### ISSUE TITLE
ML Kitchen #8

### ISSUE THREAD

**Issue by lunardog** [tokyo-ml/tokyo-ml.github.io#10]
Starting discussion on the next ML Kitchen.

@uhho mentioned maybe doing a presentation.

Looking for more speakers.

**Comment by lunardog** [comment]
Suzana (who joined the last ML Kitchen) mentioned maybe doing a talk about natural language processing. That will be two speakers.

One more and it's a GO!

**Comment by vanhuyz** [comment]
Hi @lunardog 
I can give a talk :)

**Comment by yoheikikuta** [comment]
:tada:

**Comment by vanhuyz** [comment]
Thanks! April 12th works for me.

**Comment by lunardog** [comment]
Closing this old issue.
