### ISSUE TITLE
2019-01 ML Kitchen

### ISSUE THREAD

**Issue by lunardog** [tokyo-ml/tokyo-ml.github.io#20]
- [x] apply for venue
 - [ ] find speakers

**Comment by vanhuyz** [comment]
I invited @nptdat to give a talk. Let's discuss topic and schedule here 😄

**Comment by lunardog** [comment]
Possible days for ML Kitchen:

https://chouseisan.com/s?h=2657a3efad524a74827d03a940964506

**Comment by lunardog** [comment]
Selected January 17th. Applying.

**Comment by chie8842** [comment]
:tada:

**Comment by lunardog** [comment]
I added @saurabhbhadada to this issue.
