### ISSUE TITLE
February Event

### ISSUE THREAD

**Issue by lunardog** [tokyo-ml/tokyo-ml.github.io#6]
Hi all! @ashleysmart @uhho @kenneyd @yoheikikuta  @ayemos 

How about a meetup in February?

In January we have Dev Japan and [NIPS Paper Reading](https://cookpad.connpass.com/event/74937/) here at Cookpad, so February would be the earliest for this venue.

Please spread the news in your that we're looking for speakers (speak yourself if you can). 

I'd like to do a topic, but it's been so long, any topic is fine!

- [x] find speakers
- [x] book venue
- [x] organize food and drinks
- [x] have fun

Speakers:

1. @ashleysmart 
2. @yoheikikuta 
3. @takahi-i 
4. @lunardog

**Comment by ashleysmart** [comment]
Yea I might be able to put a talk together I'm playing with satelite data at the moment can report some practical results, lessons learned etc... Code is over here: https://github.com/ashleysmart/kaggle_share/tree/master/dstl_sat_images

**Comment by ashleysmart** [comment]
I'll push an update to the public version this weekend

**Comment by lunardog** [comment]
That would be great @ashleysmart. Can you spread the news around?

**Comment by uhho** [comment]
Thanks for invitation! I will spread the news.

I can talk about processing pipelines we're using for satellite imagery analysis at Axelspace. Somehthing about tools, algorithms and challenges of remote sensing in general. :artificial_satellite: 
This could be a nice introduction (or addition) to what @ashleysmart is going to talk about.

**Comment by lunardog** [comment]
First thing that comes to mind about "remote sensing":
![remote sensing](https://pbs.twimg.com/media/CjkaHtsVAAQWqpM.jpg)

Would like to hear what it's really about. Would a weekday evening or week-end lunchtime be better for you both?

**Comment by uhho** [comment]
:smile_cat: 
Weekday evening is much better for me.

**Comment by ashleysmart** [comment]
+1 for weekday evening
And your nips event is at 157 ppl, for only 60 seats. that's crazy..  if you can stream it that would be great  and maybe should have a highlights talk in Feb?

**Comment by lunardog** [comment]
@ashleysmart @uhho Which is better for yous: 
- Thursday the 15th or 
- Friday the 16th?

**Comment by ashleysmart** [comment]
Either is fine for me.. maybe prefer the 15th

**Comment by ashleysmart** [comment]
Ok I have my title 

"Bayesian optimisation: studied against the dark art of hyper-param optimisation"

**Comment by lunardog** [comment]
Updated, thanks!

**Comment by lunardog** [comment]
Thank you! Closing this issue as the next one is already open.
